name: slugify3
version: 3.0.0
description: >-
  Converts a string into a slug. Useful for URLs, filenames, IDs, and more.
homepage: https://github.com/AlexMeuer/slugify2
documentation: https://github.com/AlexMeuer/slugify2/blob/master/README.md
environment:
  sdk: ">=2.12.0 <3.0.0"
dev_dependencies:
  test: ^1.15.3
  effective_dart: ^1.2.4
