name: slugify
version: 1.0.0
description: >-
  Converts strings into slugs, for pretty URLs
author: izolate <izolate@gmail.com>
homepage: https://github.com/izolate/slugify
documentation: https://github.com/izolate/slugify/blob/master/README.md
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  test: ^1.6.2
